

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    

spring:  
  cloud:
   gateway:
     routes:
      - id: CUSTOMERSERVICE
        uri: http://localhost:8083/
        predicates:
        - Path=/customer-service/**
        filters:
           - AuthenticationFilter               
      - id: BOOK-SERVICE
        uri: http://localhost:8081/
        predicates:
        - Path=/book-service/**
        filters:
           - AuthenticationFilter
        
        
      - id: CARTSERVICE
        uri: http://localhost:8082/
        predicates:
        - Path=/cart-service/**
        filters:
           - AuthenticationFilter
        
        
      - id: ORDERZZZSERVICE
        uri: http://localhost:8111/
        predicates:
        - Path= /orderzzz-service/**
        filters:
           - AuthenticationFilter
        
      - id:  JWT-SERVICE
        uri: http://localhost:1111/
        predicates:
        - Path=/authentication/**
        filters:
           - AuthenticationFilter
        